// State data for programmatic pages
const STATES = [
  { slug: 'andhrapradesh', name: 'Andhra Pradesh', short: 'AP', region: 'South', neighbors: ['telangana', 'tamilnadu', 'karnataka', 'odisha', 'chhattisgarh'] },
  { slug: 'arunachalpradesh', name: 'Arunachal Pradesh', short: 'AR', region: 'Northeast', neighbors: ['assam', 'nagaland'] },
  { slug: 'assam', name: 'Assam', short: 'AS', region: 'Northeast', neighbors: ['arunachalpradesh', 'nagaland', 'manipur', 'mizoram', 'tripura', 'meghalaya', 'westbengal'] },
  { slug: 'bihar', name: 'Bihar', short: 'BR', region: 'East', neighbors: ['uttarpradesh', 'jharkhand', 'westbengal'] },
  { slug: 'chhattisgarh', name: 'Chhattisgarh', short: 'CG', region: 'Central', neighbors: ['madhyapradesh', 'uttarpradesh', 'jharkhand', 'odisha', 'telangana', 'maharashtra'] },
  { slug: 'delhi', name: 'Delhi (NCT)', short: 'DL', region: 'North', neighbors: ['haryana', 'uttarpradesh'] },
  { slug: 'goa', name: 'Goa', short: 'GA', region: 'West', neighbors: ['maharashtra', 'karnataka'] },
  { slug: 'gujarat', name: 'Gujarat', short: 'GJ', region: 'West', neighbors: ['rajasthan', 'madhyapradesh', 'maharashtra'] },
  { slug: 'haryana', name: 'Haryana', short: 'HR', region: 'North', neighbors: ['punjab', 'himachalpradesh', 'uttarpradesh', 'rajasthan', 'delhi'] },
  { slug: 'himachalpradesh', name: 'Himachal Pradesh', short: 'HP', region: 'North', neighbors: ['punjab', 'haryana', 'uttarakhand'] },
  { slug: 'jharkhand', name: 'Jharkhand', short: 'JH', region: 'East', neighbors: ['bihar', 'uttarpradesh', 'chhattisgarh', 'odisha', 'westbengal'] },
  { slug: 'karnataka', name: 'Karnataka', short: 'KA', region: 'South', neighbors: ['maharashtra', 'goa', 'kerala', 'tamilnadu', 'andhrapradesh', 'telangana'] },
  { slug: 'kerala', name: 'Kerala', short: 'KL', region: 'South', neighbors: ['karnataka', 'tamilnadu'] },
  { slug: 'madhyapradesh', name: 'Madhya Pradesh', short: 'MP', region: 'Central', neighbors: ['rajasthan', 'uttarpradesh', 'chhattisgarh', 'maharashtra', 'gujarat'] },
  { slug: 'maharashtra', name: 'Maharashtra', short: 'MH', region: 'West', neighbors: ['gujarat', 'madhyapradesh', 'chhattisgarh', 'telangana', 'karnataka', 'goa'] },
  { slug: 'manipur', name: 'Manipur', short: 'MN', region: 'Northeast', neighbors: ['assam', 'nagaland', 'mizoram'] },
  { slug: 'meghalaya', name: 'Meghalaya', short: 'ML', region: 'Northeast', neighbors: ['assam'] },
  { slug: 'mizoram', name: 'Mizoram', short: 'MZ', region: 'Northeast', neighbors: ['assam', 'manipur', 'tripura'] },
  { slug: 'nagaland', name: 'Nagaland', short: 'NL', region: 'Northeast', neighbors: ['arunachalpradesh', 'assam', 'manipur'] },
  { slug: 'odisha', name: 'Odisha', short: 'OD', region: 'East', neighbors: ['westbengal', 'jharkhand', 'chhattisgarh', 'andhrapradesh'] },
  { slug: 'punjab', name: 'Punjab', short: 'PB', region: 'North', neighbors: ['himachalpradesh', 'haryana', 'rajasthan'] },
  { slug: 'rajasthan', name: 'Rajasthan', short: 'RJ', region: 'North', neighbors: ['punjab', 'haryana', 'uttarpradesh', 'madhyapradesh', 'gujarat'] },
  { slug: 'sikkim', name: 'Sikkim', short: 'SK', region: 'Northeast', neighbors: ['westbengal'] },
  { slug: 'tamilnadu', name: 'Tamil Nadu', short: 'TN', region: 'South', neighbors: ['kerala', 'karnataka', 'andhrapradesh'] },
  { slug: 'telangana', name: 'Telangana', short: 'TS', region: 'South', neighbors: ['andhrapradesh', 'karnataka', 'maharashtra', 'chhattisgarh', 'odisha'] },
  { slug: 'tripura', name: 'Tripura', short: 'TR', region: 'Northeast', neighbors: ['assam', 'mizoram'] },
  { slug: 'uttarpradesh', name: 'Uttar Pradesh', short: 'UP', region: 'North', neighbors: ['uttarakhand', 'himachalpradesh', 'haryana', 'delhi', 'rajasthan', 'madhyapradesh', 'chhattisgarh', 'jharkhand', 'bihar'] },
  { slug: 'uttarakhand', name: 'Uttarakhand', short: 'UK', region: 'North', neighbors: ['himachalpradesh', 'uttarpradesh'] },
  { slug: 'westbengal', name: 'West Bengal', short: 'WB', region: 'East', neighbors: ['sikkim', 'assam', 'meghalaya', 'bihar', 'jharkhand', 'odisha'] },
];

// Stamp duty rates summary for display
const STAMP_DUTY_RATES = {
  andhrapradesh: { male: '5%', female: '4%', joint: '4.5%', reg: '1%' },
  arunachalpradesh: { male: '5%', female: '4%', joint: '4.5%', reg: '1%' },
  assam: { male: '6%', female: '6%', joint: '6%', reg: '1.5%' },
  bihar: { male: '6%', female: '5%', joint: '5.5%', reg: '2%' },
  chhattisgarh: { male: '5%', female: '4%', joint: '4.5%', reg: '1%' },
  delhi: { male: '6%', female: '4%', joint: '5%', reg: '1%' },
  goa: { male: '6.5%', female: '6.5%', joint: '6.5%', reg: '1%' },
  gujarat: { male: '4.9%', female: '4.9%', joint: '4.9%', reg: '1%' },
  haryana: { male: '6%', female: '5%', joint: '5.5%', reg: '1%' },
  himachalpradesh: { male: '6%', female: '5%', joint: '5.5%', reg: '1%' },
  jharkhand: { male: '5%', female: '4%', joint: '4.5%', reg: '1%' },
  karnataka: { male: '5%', female: '5%', joint: '5%', reg: '1% (+10% cess)' },
  kerala: { male: '8%', female: '6%', joint: '7%', reg: '2% (+10% surcharge)' },
  madhyapradesh: { male: '6%', female: '5%', joint: '5.5%', reg: '1%' },
  maharashtra: { male: '6%', female: '5%', joint: '5.5%', reg: '1% (cap ₹30K)' },
  manipur: { male: '5%', female: '4%', joint: '4.5%', reg: '1%' },
  meghalaya: { male: '5%', female: '4%', joint: '4.5%', reg: '1%' },
  mizoram: { male: '5%', female: '4%', joint: '4.5%', reg: '1%' },
  nagaland: { male: '5%', female: '4%', joint: '4.5%', reg: '1%' },
  odisha: { male: '6%', female: '5%', joint: '5.5%', reg: '1.5%' },
  punjab: { male: '6%', female: '5%', joint: '5.5%', reg: '1%' },
  rajasthan: { male: '6%', female: '5%', joint: '5.5%', reg: '1%' },
  sikkim: { male: '6%', female: '5%', joint: '5.5%', reg: '1%' },
  tamilnadu: { male: '6%', female: '6%', joint: '6%', reg: '4%' },
  telangana: { male: '6%', female: '5%', joint: '5.5%', reg: '1%' },
  tripura: { male: '5%', female: '4%', joint: '4.5%', reg: '1%' },
  uttarpradesh: { male: '6%', female: '5%', joint: '5.5%', reg: '1%' },
  uttarakhand: { male: '6%', female: '5%', joint: '5.5%', reg: '1%' },
  westbengal: { male: '6%', female: '5%', joint: '5.5%', reg: '1.5% (+1.5% cess)' },
};

// RTO tax summary (simplified for display)
const RTO_RATES = {
  andhrapradesh: '12-14%',
  arunachalpradesh: '6-8%',
  assam: '8-10%',
  bihar: '8-12%',
  chhattisgarh: '7-9%',
  delhi: '4-12%',
  goa: '9-11%',
  gujarat: '6-9%',
  haryana: '8-10%',
  himachalpradesh: '5-7%',
  jharkhand: '6-8%',
  karnataka: '10-18%',
  kerala: '6-15%',
  madhyapradesh: '8-12%',
  maharashtra: '11-15%',
  manipur: '6-8%',
  meghalaya: '6-8%',
  mizoram: '5-7%',
  nagaland: '5-7%',
  odisha: '8-12%',
  punjab: '6-10%',
  rajasthan: '6-10%',
  sikkim: '6-8%',
  tamilnadu: '10-15%',
  telangana: '9-14%',
  tripura: '6-8%',
  uttarpradesh: '7-10%',
  uttarakhand: '5-8%',
  westbengal: '10-12%',
};

// Export for Node.js
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { STATES, STAMP_DUTY_RATES, RTO_RATES };
}