name = "desicalc"
type = "pages"
pages_build_output_dir = "public"

# [env.production]
# routes = ["*desicalc.in/*"]
# [env.preview]
# routes = ["*desicalc.pages.dev/*"]


[env.production]
routes = ["*desicalc.pages.dev/*"]
